import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { toast } from "react-toastify";
import { useAuth } from "../context/AuthContext.jsx";

const Register = () => {
  const navigate = useNavigate(); const { setAuthUser } = useAuth();
  const [loading, setLoading] = useState(false); const [inputData, setInputData] = useState({});
  const update = (event) => setInputData({ ...inputData, [event.target.id]: event.target.value });
  const handleSubmit = async (event) => { event.preventDefault(); if (inputData.password !== inputData.confirmpassword) return toast.error("Passwords don't match"); setLoading(true); try { const { data } = await axios.post("/api/auth/register", inputData); toast.success(data.message); localStorage.setItem("chatapp", JSON.stringify(data)); setAuthUser(data); navigate("/"); } catch (error) { toast.error(error?.response?.data?.message || "Unable to create account"); } finally { setLoading(false); } };
  const field = (id, label, type = "text", placeholder = "") => <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-200">{label}</span><input id={id} type={type} onChange={update} placeholder={placeholder} required className="w-full rounded-xl border border-white/10 bg-white/[.07] px-4 py-2.5 text-white outline-none transition placeholder:text-slate-500 focus:border-violet-400" /></label>;
  return <div className="glass-panel w-full max-w-lg rounded-[2rem] p-6 shadow-2xl shadow-black/30 sm:p-8"><div className="mb-6"><div className="mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-indigo-600 text-lg font-black">C</div><p className="text-sm font-semibold uppercase tracking-[.2em] text-violet-300">Join Chatters</p><h1 className="mt-1 text-3xl font-bold text-white">Your people are waiting.</h1></div><form onSubmit={handleSubmit} className="grid gap-3 sm:grid-cols-2">{field("fullname", "Full name", "text", "Jane Doe")}{field("username", "Username", "text", "janedoe")}{field("email", "Email address", "email", "you@example.com")}<div className="sm:col-span-2 grid gap-3 sm:grid-cols-2">{field("password", "Password", "password", "At least 8 characters")}{field("confirmpassword", "Confirm password", "password", "Repeat password")}</div><div className="sm:col-span-2"><p className="mb-2 text-sm font-medium text-slate-200">I identify as</p><div className="flex gap-3"><button type="button" onClick={() => setInputData({ ...inputData, gender: "male" })} className={`rounded-xl px-4 py-2 text-sm transition ${inputData.gender === "male" ? "bg-violet-500 text-white" : "bg-white/[.07] text-slate-300"}`}>Male</button><button type="button" onClick={() => setInputData({ ...inputData, gender: "female" })} className={`rounded-xl px-4 py-2 text-sm transition ${inputData.gender === "female" ? "bg-violet-500 text-white" : "bg-white/[.07] text-slate-300"}`}>Female</button></div></div><button type="submit" disabled={loading} className="sm:col-span-2 mt-2 w-full rounded-xl bg-gradient-to-r from-violet-500 to-indigo-600 px-4 py-3 font-semibold text-white shadow-lg shadow-violet-950/30 transition hover:brightness-110 disabled:opacity-60">{loading ? "Creating account..." : "Create account"}</button></form><p className="mt-5 text-center text-sm text-slate-400">Already here? <Link to="/login" className="font-semibold text-violet-300 hover:text-violet-200">Sign in</Link></p></div>;
};
export default Register;

